# Generated by Django 5.2.8 on 2025-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload featured image",
                null=True,
                upload_to="blog/images/",
            ),
        ),
    ]
