# Generated by Django 5.2.8 on 2025-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., 'fa-python')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db", help_text="Hex color code", max_length=7
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(help_text="One-line description", max_length=200),
                ),
                (
                    "image",
                    models.URLField(blank=True, help_text="Project screenshot URL"),
                ),
                ("demo_url", models.URLField(blank=True, help_text="Live demo URL")),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("planned", "Planned"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projects", to="portfolio.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
