# Generated by Django 5.2.8 on 2025-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload project screenshot",
                null=True,
                upload_to="portfolio/images/",
            ),
        ),
    ]
