# Generated by Django 5.2.8 on 2025-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("start_year", models.CharField(max_length=10)),
                ("end_year", models.CharField(max_length=10)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=200)),
                ("linkedin", models.URLField(blank=True)),
                ("summary", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("soft", "Soft Skills"),
                            ("methodology", "Methodologies"),
                            ("programming", "Programming Languages"),
                            ("database", "Databases"),
                            ("tool", "Tools"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
    ]
